# Site settings
title: Rajat Bhatnagar
email: Rajat_Bhatnagar@outlook.com
description: "An individual's assimilation of thoughts and learnings about software patterns, design, development, creation and delivery."
baseurl: ""
url: "http://rajat-bhatnagar.github.io"
twitter_username: Rajat_Bhatnagar
github_username:  Rajat-Bhatnagar
facebook_username: Bhatnagar.Rajat
linkedin_username: rajatbhatnagar

tagline: "Guide to Software Development Experience"

# Build settings
markdown: kramdown

# Other options
permalink: writing/:year/:month/:title
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

#Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
exclude: [vendor]

#Allow future posts with a date in future to be published
future: true

#Add favicon
favicon: "/images/favicon.ico"